repos:
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        args:
          - summarizer
          - summarizer-resources/tests
#-   repo: https://github.com/pycqa/isort
    #rev: 5.9.2
    #hooks:
    #-   id: isort
        #args:
          #- tests style
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
      exclude: ^tests/fixtures/diffs/
-   repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
    - id: black
      language_version: python3.11
      args:
        - --exclude=/(\.eggs|\.git|\.hg|\.venv|build|dist|portfolio|)/
        - --target-version=py311
        - -l 80
-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: bash -c 'make test'
        language: system
        pass_filenames: false
        types: [python]
        stages: [push]
        verbose: true
