version: "3.11"
services:

  summarizer:
    build:
      dockerfile: Dockerfile
    image: summarizer
    command: sleep 3600
    volumes:
      - ./summarizer:/applications/summarizer
    ports:
      - "8000:8000"
    networks:
      - backend
    restart: "no"
    env_file: .env

networks:
  backend:

volumes:
  db-data: { }
